# Generated by Django 5.2.15 on 2026-06-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_media', '0004_hotelmediaitem_organization'),
        ('organizations', '0004_organization_deleted_at_organization_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram')], default='instagram', max_length=30)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Platform media/story/post ID when available', max_length=128)),
                ('parent_external_id', models.CharField(blank=True, db_index=True, help_text='Parent post/reel/highlight ID for derived story or share events', max_length=128)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('story', 'Story'), ('highlight', 'Highlight'), ('event', 'Event / Campaign'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=30)),
                ('review_status', models.CharField(choices=[('auto', 'Auto-tagged'), ('needs_review', 'Needs manager review'), ('reviewed', 'Reviewed')], default='needs_review', max_length=30)),
                ('source', models.CharField(choices=[('auto_sync', 'Auto sync'), ('webhook', 'Webhook'), ('manual', 'Manual')], default='auto_sync', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('rooms', 'Guest Rooms'), ('cafeteria', 'Cafeteria & Dining'), ('pool', 'Pool'), ('spa', 'Spa & Wellness'), ('conference', 'Conference & Events'), ('exterior', 'Exterior & Views'), ('lobby', 'Lobby & Common Areas'), ('other', 'Other')], help_text='Main topic/category managers and AI should use for this content', max_length=50)),
                ('room_category', models.CharField(blank=True, choices=[('standard_queen', 'Standard Queen'), ('standard_twin', 'Standard Twin'), ('comfort', 'Comfort'), ('family', 'Family'), ('other', 'Other')], help_text='Room type if this content is about a specific room category', max_length=50, null=True)),
                ('playbook_keys', models.JSONField(blank=True, default=list, help_text='Optional playbook keys to prefer when a guest replies to this content')),
                ('auto_tags', models.JSONField(blank=True, default=list)),
                ('reply_guidance', models.TextField(blank=True, help_text='Short manager-approved guidance/template for replies to this content')),
                ('manager_notes', models.TextField(blank=True)),
                ('media_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('permalink', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_media_item', models.ForeignKey(blank=True, help_text='Curated hotel media item this social content represents, if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_content_items', to='hotel_media.hotelmediaitem')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Social Content Item',
                'verbose_name_plural': 'Social Content Items',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_kind', models.CharField(choices=[('phash', 'Perceptual hash'), ('dhash', 'Difference hash'), ('ahash', 'Average hash'), ('center_phash', 'Center-crop perceptual hash'), ('colorhash', 'Color hash')], max_length=30)),
                ('hash_value', models.CharField(max_length=256)),
                ('bit_length', models.PositiveSmallIntegerField(default=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_second', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('crop_label', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='hotel_media.hotelmediaitem')),
                ('hotel_media_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='hotel_media.hotelmediaphoto')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('social_content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='hotel_media.socialcontentitem')),
            ],
            options={
                'verbose_name': 'Media Fingerprint',
                'verbose_name_plural': 'Media Fingerprints',
                'ordering': ['hash_kind', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='socialcontentitem',
            index=models.Index(fields=['organization', 'platform', 'content_type', 'status'], name='hotel_media_organiz_5b0244_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcontentitem',
            index=models.Index(fields=['organization', 'review_status'], name='hotel_media_organiz_0e3a13_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcontentitem',
            index=models.Index(fields=['expires_at'], name='hotel_media_expires_cc39a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialcontentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('organization', 'platform', 'external_id'), name='uniq_social_content_external_id_per_org'),
        ),
        migrations.AddIndex(
            model_name='mediafingerprint',
            index=models.Index(fields=['organization', 'hash_kind'], name='hotel_media_organiz_598e36_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafingerprint',
            index=models.Index(fields=['hash_kind', 'hash_value'], name='hotel_media_hash_ki_243bba_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafingerprint',
            index=models.Index(fields=['hotel_media_item'], name='hotel_media_hotel_m_b494be_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafingerprint',
            index=models.Index(fields=['social_content_item'], name='hotel_media_social__fe4873_idx'),
        ),
    ]
