# Generated by Django 5.2.14 on 2026-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0021_agentconfig_organization_aiflowmode_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='aitool',
            name='parameters_schema',
            field=models.JSONField(blank=True, help_text='JSON schema for tool parameters', null=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='runtime_config',
            field=models.JSONField(blank=True, help_text='Runtime config settings', null=True),
        ),
        migrations.AddConstraint(
            model_name='aitool',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='flows_aitool_unique_org_name'),
        ),
    ]
