# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0022_aitool_parameters_schema_aitool_runtime_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcard',
            name='goal',
            field=models.TextField(blank=True, default='', help_text='Business goal for this stage, e.g. collect dates or qualify the lead.'),
        ),
        migrations.AddField(
            model_name='flowcard',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, help_text='Lead/custom field names that should be collected before leaving this stage.'),
        ),
        migrations.AddField(
            model_name='flowcard',
            name='success_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Structured conditions that mark this stage as complete.'),
        ),
        migrations.AddField(
            model_name='flowcard',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of AI tool names allowed while this card is active.'),
        ),
        migrations.AddField(
            model_name='flowcard',
            name='response_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Stage-specific response rules such as answer_then_return or max length.'),
        ),
        migrations.AddField(
            model_name='flowcard',
            name='return_to_funnel_instruction',
            field=models.TextField(blank=True, default='', help_text='Instruction for returning to this stage after side questions.'),
        ),
    ]
