# Generated by Django 5.2.15 on 2026-06-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0023_flowcard_stage_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managertransferconfig',
            name='notification_template',
            field=models.TextField(blank=True, help_text='Custom notification message template. Leave blank to use the default. Available variables: {reason}, {guest_name}, {guest_phone}, {guest_email}, {platform}, {checkin_date}, {checkout_date}, {nights}, {guest_count}, {room_description}, {meal_plan}, {price_per_night}, {total_price}, {discovery_source}, {discovery_source_detail}, {notes}, {contact_id}, {business_name}'),
        ),
    ]
