# Generated by Django 5.2.14 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_tax_accountant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Manager'), ('support', 'Support'), ('tax_accountant', 'Tax Accountant')], default='support', max_length=50),
        ),
    ]
