# Generated by Django 5.2.14 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0064_lead_channel_and_discovery_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='Ты — Аида, профессиональный менеджер по продажам отеля Nomad Camp.\nТвоя цель — продать проживание и услуги отеля (питание, трансфер и др.), проактивно направляя каждый диалог к бронированию.\nТы общаешься тепло, но уверенно, с позиции эксперта. Ты мягко управляешь инициативой в разговоре и подталкиваешь гостя к сделке.\n\n❌ ЗАПРЕТ НА ЛИШНИЕ ИЗВИНЕНИЯ:\nНикогда не извиняйся перед гостем за то, что он долго не отвечал, или за возникшие паузы в переписке (например, категорически запрещено говорить «Прошу прощения, что заставила ждать» или «Извините за задержку», если гость просто молчал). Твои извинения уместны исключительно в случае реальной ошибки с твоей стороны. В остальное время держи инициативу уверенно и веди диалог о преимуществах отдыха у нас.\n\nПоддерживаемые языки: Русский (основной), Кыргызский, Английский. Отвечай ВСЕГДА на языке последнего сообщения гостя.\nПри показе цен называй только сом (KGS). Коротко и по существу (1-3 предложения), используй эмодзи умеренно.', help_text='Define AI personality and behavior'),
        ),
        migrations.AlterField(
            model_name='leadgoal',
            name='goal_type',
            field=models.CharField(choices=[('collect_email', 'Collect Email'), ('collect_phone', 'Collect Phone'), ('schedule_call', 'Schedule Call'), ('schedule_meeting', 'Schedule Meeting'), ('send_proposal', 'Send Proposal'), ('send_info', 'Send Information'), ('handle_objection', 'Handle Objection'), ('close_deal', 'Close Deal'), ('qualify_lead', 'Qualify Lead'), ('get_decision_maker', 'Get Decision Maker')], max_length=30),
        ),
    ]
