# Generated by Django 5.2.14 on 2026-06-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0022_roomcombinationnote_organization'),
        ('organizations', '0004_organization_deleted_at_organization_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Reply Template Category',
                'verbose_name_plural': 'Reply Template Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='hotel_info.replytemplatecategory')),
            ],
            options={
                'verbose_name': 'Reply Template',
                'verbose_name_plural': 'Reply Templates',
                'ordering': ['order', 'id'],
            },
        ),
    ]
